---
branches:
  - name: "main"
  - name: "feature/*"
    prerelease: "rc"

plugins:
  - "@semantic-release/commit-analyzer"
  - "@semantic-release/release-notes-generator"
  - "@semantic-release/github"
...
