---
extends: "default"

rules:
  line-length:
    max: 120
    level: "warning"
  document-start:
    level: "error"
  document-end:
    level: "error"
  quoted-strings:
    quote-type: "double"
    level: "warning"
...
