---
extends: "default"

ignore:
  - "*"
  - "!chart/dist/"

rules:
  line-length:
    max: 140
    level: "error"
  document-start:
    level: "error"
  quoted-strings:
    quote-type: "double"
    level: "warning"
