{{- if .Values.onlyRenderDashboardJson }}
    {{- include "dashboard.json" . }}
{{- else }}
---
kind: "ConfigMap"
apiVersion: {{ .Values.apiVersions.configMap | quote }}
metadata:
  name: {{ include "names.fullname" . | quote }}
  namespace: {{ include "names.namespace" . | quote }}
  labels:
    {{- include "labels.commonLabels" . | nindent 4 }}
    {{- with .Values.extraLabels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
data:
  {{ include "names.fullname" . }}.json: |
    {{- include "dashboard.json" . | nindent 4 }}
...
{{- end}}
